import type { RendererTarget } from './types.js';

export interface VersionMapEntry {
  readonly canonical: string;
  readonly aliases: Partial<Record<RendererTarget, string>>;
  readonly classification: 'schema-simple' | 'schema-raw' | 'pg-only' | 'disabled';
  readonly notes?: string;
}

export const VERSION_MAP: readonly VersionMapEntry[] = [
  { canonical: 'v001', aliases: { postgres: 'v001', 'sqlite-sql': 'v001' }, classification: 'schema-simple' },
  { canonical: 'v002', aliases: { postgres: 'v002', 'sqlite-sql': 'v002' }, classification: 'schema-simple' },
  { canonical: 'v003', aliases: { postgres: 'v003', 'sqlite-sql': 'v003' }, classification: 'schema-simple' },
  { canonical: 'v004', aliases: { postgres: 'v004', 'sqlite-sql': 'v004' }, classification: 'schema-simple' },
  { canonical: 'v005', aliases: { postgres: 'v005', 'sqlite-sql': 'v005' }, classification: 'schema-simple' },
  { canonical: 'v006', aliases: { postgres: 'v006', 'sqlite-sql': 'v006' }, classification: 'schema-simple' },
  { canonical: 'v007', aliases: { postgres: 'v007', 'sqlite-sql': 'v007' }, classification: 'schema-raw', notes: 'SQLite 表重建 vs PG 原地 ALTER' },
  { canonical: 'v008', aliases: { postgres: 'v008', 'sqlite-sql': 'v008' }, classification: 'schema-simple' },
  { canonical: 'v009', aliases: { postgres: 'v009', 'sqlite-sql': 'v009' }, classification: 'schema-simple' },
  { canonical: 'v010', aliases: { postgres: 'v010', 'sqlite-sql': 'v010' }, classification: 'schema-simple' },
  { canonical: 'v011', aliases: { postgres: 'v011', 'sqlite-sql': 'v011' }, classification: 'schema-simple' },
  { canonical: 'v012', aliases: { postgres: 'v012', 'sqlite-sql': 'v012' }, classification: 'schema-simple' },
  { canonical: 'v013', aliases: { postgres: 'v013', 'sqlite-sql': 'v013' }, classification: 'schema-simple' },
  { canonical: 'v014', aliases: { postgres: 'v014', 'sqlite-sql': 'v014' }, classification: 'schema-simple' },
  { canonical: 'v015', aliases: { postgres: 'v015', 'sqlite-sql': 'v015' }, classification: 'schema-simple' },
  { canonical: 'v016', aliases: { postgres: 'v016', 'sqlite-sql': 'v016' }, classification: 'schema-simple' },
  { canonical: 'v017', aliases: { postgres: 'v017', 'sqlite-sql': 'v017' }, classification: 'schema-simple' },
  { canonical: 'v018', aliases: { postgres: 'v018', 'sqlite-sql': 'v018' }, classification: 'schema-simple' },
  { canonical: 'v019', aliases: { postgres: 'v019', 'sqlite-sql': 'v019' }, classification: 'schema-simple' },
  { canonical: 'v020', aliases: { postgres: 'v020', 'sqlite-sql': 'v020' }, classification: 'schema-simple' },
  { canonical: 'v021', aliases: { postgres: 'v021', 'sqlite-sql': 'v021' }, classification: 'schema-simple' },
  { canonical: 'v022', aliases: { postgres: 'v022', 'sqlite-sql': 'v022' }, classification: 'schema-simple' },
  { canonical: 'v023', aliases: { postgres: 'v023', 'sqlite-sql': 'v023' }, classification: 'schema-simple' },
  { canonical: 'v024', aliases: { postgres: 'v024', 'sqlite-sql': 'v024' }, classification: 'schema-simple' },
  { canonical: 'v025', aliases: { postgres: 'v025', 'sqlite-sql': 'v025' }, classification: 'schema-simple' },
  { canonical: 'v026', aliases: { postgres: 'v026', 'sqlite-sql': 'v026' }, classification: 'schema-simple' },
  { canonical: 'v027', aliases: { postgres: 'v027', 'sqlite-sql': 'v027' }, classification: 'schema-raw', notes: 'identities/avatars 回填 DML' },
  { canonical: 'v028', aliases: { postgres: 'v028', 'sqlite-sql': 'v028' }, classification: 'schema-simple' },
  { canonical: 'v029', aliases: { postgres: 'v029', 'sqlite-sql': 'v029' }, classification: 'schema-simple' },
  { canonical: 'v030', aliases: { postgres: 'v030', 'sqlite-sql': 'v030' }, classification: 'schema-raw', notes: 'CHECK 约束改写' },
  { canonical: 'v031', aliases: { postgres: 'v031', 'sqlite-sql': 'v031' }, classification: 'schema-simple' },
  { canonical: 'v032', aliases: { postgres: 'v032', 'sqlite-sql': 'v032' }, classification: 'schema-simple' },
  { canonical: 'v033', aliases: { postgres: 'v033', 'sqlite-sql': 'v033' }, classification: 'schema-simple' },
  { canonical: 'v034', aliases: { postgres: 'v034', 'sqlite-sql': 'v034' }, classification: 'schema-raw', notes: 'lifecycle_status 回填；NULL 语义差异原样保留' },
  { canonical: 'v035', aliases: { postgres: 'v035', 'sqlite-sql': 'v035' }, classification: 'schema-simple' },
  { canonical: 'v036', aliases: { postgres: 'v036', 'sqlite-sql': 'v036' }, classification: 'schema-simple' },
  { canonical: 'v037', aliases: { postgres: 'v037', 'sqlite-sql': 'v037' }, classification: 'schema-simple' },
  { canonical: 'v038', aliases: { postgres: 'v038', 'sqlite-sql': 'v038' }, classification: 'schema-simple' },
  { canonical: 'v039', aliases: { postgres: 'v039', 'sqlite-sql': 'v039' }, classification: 'schema-simple' },
  { canonical: 'v040', aliases: { postgres: 'v040', 'sqlite-sql': 'v040' }, classification: 'schema-raw', notes: 'audit_log 回填 UPDATE' },
  { canonical: 'v041', aliases: { postgres: 'v041', 'sqlite-sql': 'v041' }, classification: 'schema-raw', notes: 'runtime_sessions 重建/CHECK/UPDATE' },
  { canonical: 'v042', aliases: { postgres: 'v042', 'sqlite-sql': 'v042' }, classification: 'schema-simple' },
  { canonical: 'v043', aliases: { postgres: 'v043', 'sqlite-sql': 'v043' }, classification: 'schema-simple' },
  { canonical: 'v044', aliases: { postgres: 'v044', 'sqlite-sql': 'v044' }, classification: 'schema-simple' },
  { canonical: 'v045', aliases: { postgres: 'v045', 'sqlite-sql': 'v045' }, classification: 'schema-simple' },
  { canonical: 'v046', aliases: { postgres: 'v046', 'sqlite-sql': 'v046' }, classification: 'schema-simple' },
  { canonical: 'v047', aliases: { postgres: 'v047', 'sqlite-sql': 'v047' }, classification: 'schema-raw', notes: 'identity/avatar 多表重建' },
  { canonical: 'v048', aliases: { postgres: 'v048', 'sqlite-sql': 'v048' }, classification: 'schema-simple' },
  { canonical: 'v049', aliases: { postgres: 'v049', 'sqlite-sql': 'v049' }, classification: 'schema-simple' },
  { canonical: 'v050', aliases: { postgres: 'v050', 'sqlite-sql': 'v050' }, classification: 'schema-simple' },
  { canonical: 'v051', aliases: { postgres: 'v051', 'sqlite-sql': 'v051' }, classification: 'schema-simple' },
  { canonical: 'v052', aliases: { postgres: 'v052', 'sqlite-sql': 'v052' }, classification: 'schema-raw', notes: 'event_ledger_authority 单例 seed' },
  { canonical: 'v053', aliases: { postgres: 'v053', 'sqlite-sql': 'v053' }, classification: 'schema-simple' },
  { canonical: 'v054', aliases: { postgres: 'v054', 'sqlite-sql': 'v054' }, classification: 'schema-simple' },
  { canonical: 'v055', aliases: { postgres: 'v055', 'sqlite-sql': 'v055' }, classification: 'schema-simple' },
  { canonical: 'v056', aliases: { postgres: 'v056', 'sqlite-sql': 'v056' }, classification: 'schema-simple' },
  { canonical: 'v057', aliases: { postgres: 'v057', 'sqlite-sql': 'v057' }, classification: 'schema-simple' },
  { canonical: 'v058', aliases: { postgres: 'v058', 'sqlite-sql': 'v058' }, classification: 'schema-simple' },
  { canonical: 'v059', aliases: { postgres: 'v059', 'sqlite-sql': 'v059' }, classification: 'schema-simple' },
  { canonical: 'v060', aliases: { postgres: 'v060', 'sqlite-sql': 'v060' }, classification: 'schema-simple' },
  { canonical: 'v061', aliases: { postgres: 'v061', 'sqlite-sql': 'v061' }, classification: 'schema-simple' },
  { canonical: 'v062', aliases: { postgres: 'v062', 'sqlite-sql': 'v062' }, classification: 'schema-simple' },
  { canonical: 'v063', aliases: { postgres: 'v063', 'sqlite-sql': 'v063' }, classification: 'schema-simple' },
  { canonical: 'v064', aliases: { postgres: 'v064', 'sqlite-sql': 'v064' }, classification: 'schema-simple' },
  { canonical: 'v065', aliases: { postgres: 'v065', 'sqlite-sql': 'v065' }, classification: 'schema-simple' },
  { canonical: 'v066', aliases: { postgres: 'v066', 'sqlite-sql': 'v066' }, classification: 'schema-simple' },
  { canonical: 'v067', aliases: { postgres: 'v067', 'sqlite-sql': 'v067' }, classification: 'schema-simple' },
  { canonical: 'v068', aliases: { postgres: 'v068', 'sqlite-sql': 'v068' }, classification: 'schema-simple' },
  { canonical: 'v069', aliases: { postgres: 'v069', 'sqlite-sql': 'v069' }, classification: 'schema-simple' },
  { canonical: 'v070', aliases: { postgres: 'v070', 'sqlite-sql': 'v070' }, classification: 'schema-simple' },
  { canonical: 'v071_pg', aliases: { postgres: 'v071' }, classification: 'pg-only', notes: 'pgvector + HNSW + trigger' },
  { canonical: 'v072_pg', aliases: { postgres: 'v072' }, classification: 'disabled', notes: 'pgvector stage 7 — ships when ramp completes' },
  { canonical: 'v071_sqlite_devices_token', aliases: { postgres: 'v073', 'sqlite-sql': 'v071' }, classification: 'schema-simple', notes: 'EP-3.5 token invalidation; alias skew' },
  { canonical: 'v072_onboarding_v2', aliases: { postgres: 'v074', 'sqlite-sql': 'v072' }, classification: 'schema-simple', notes: 'W2.1 agent-governance onboarding; PG skips v072(disabled)/v073(devices)' },
  { canonical: 'v073_audit_hash_chain', aliases: { postgres: 'v075', 'sqlite-sql': 'v073' }, classification: 'schema-simple', notes: 'P0-E: audit_log append-only hash chain columns' },
  { canonical: 'v074_soc2_evidence', aliases: { postgres: 'v076', 'sqlite-sql': 'v074' }, classification: 'schema-simple', notes: 'P1-F-basic: SOC2 evidence collection table' },
  { canonical: 'v075_legal_holds', aliases: { postgres: 'v077', 'sqlite-sql': 'v075' }, classification: 'schema-simple', notes: 'P1-N: legal holds registry' },
  { canonical: 'v076_break_glass_jti_consumptions', aliases: { postgres: 'v078', 'sqlite-sql': 'v076' }, classification: 'schema-simple', notes: 'P1-M v2: durable break-glass JTI replay ledger' },
  { canonical: 'v077_audit_chain_anchors', aliases: { postgres: 'v079', 'sqlite-sql': 'v077' }, classification: 'schema-simple', notes: 'P0-E v2: KMS-signed audit chain tail anchors' },
  { canonical: 'v078_jwt_signing_keys', aliases: { postgres: 'v080', 'sqlite-sql': 'v078' }, classification: 'schema-simple', notes: 'P0-D #2: durable JWT signing key ring with state machine' },
  { canonical: 'v079_audit_chain_anchor_failures', aliases: { postgres: 'v081', 'sqlite-sql': 'v079' }, classification: 'schema-simple', notes: 'GA §8 #1: persist KMS anchor failures as evidence rows' },
  { canonical: 'v080_distilled_artifacts', aliases: { postgres: 'v082', 'sqlite-sql': 'v080' }, classification: 'schema-simple', notes: 'ADR-0047: gated LLM→core distillation artifact pipeline' },
  { canonical: 'v081_persona_leases', aliases: { postgres: 'v083', 'sqlite-sql': 'v081' }, classification: 'schema-simple', notes: 'ADR-0047/0048: per-persona concurrency lease (earning + compile)' },
  { canonical: 'v082_response_templates', aliases: { postgres: 'v084', 'sqlite-sql': 'v082' }, classification: 'schema-simple', notes: 'ADR-0047: durable versioned response templates (replaces decaying procedural memory)' },
  { canonical: 'v083_persona_rules', aliases: { postgres: 'v085', 'sqlite-sql': 'v083' }, classification: 'schema-simple', notes: 'ADR-0047: durable versioned persona rules for rule-engine adjustments' },
  { canonical: 'v084_llm_provider_credentials', aliases: { postgres: 'v086', 'sqlite-sql': 'v084' }, classification: 'schema-simple', notes: 'BYOK: encrypted per-tenant LLM provider API keys' },
  { canonical: 'v085_tenant_llm_settings', aliases: { postgres: 'v087', 'sqlite-sql': 'v085' }, classification: 'schema-simple', notes: 'BYOK: per-tenant active LLM provider preference' },
  { canonical: 'v086_perception_media_refs', aliases: { postgres: 'v088', 'sqlite-sql': 'v086' }, classification: 'schema-simple', notes: 'ADR-0052 Edge-P5: perception media reference metadata' },
  { canonical: 'v087_perception_events', aliases: { postgres: 'v089', 'sqlite-sql': 'v087' }, classification: 'schema-simple', notes: 'Perception layer: perception event audit' },
  { canonical: 'v088_distilled_artifacts_perception_source', aliases: { postgres: 'v090', 'sqlite-sql': 'v088' }, classification: 'schema-raw', notes: 'Perception: add perception source to distilled_artifacts CHECK (SQLite rebuild / PG alter constraint)' },
  { canonical: 'v089_distilled_compiled_via', aliases: { postgres: 'v091', 'sqlite-sql': 'v089' }, classification: 'schema-simple', notes: 'Growth governance: distilled_artifacts.compiled_via (auto vs approved) for unverified-growth budget' },
  { canonical: 'v090_persona_governance_policy', aliases: { postgres: 'v092', 'sqlite-sql': 'v090' }, classification: 'schema-simple', notes: 'Governance config: per-persona earning/AML/budget policy override (JSON blob)' },
  { canonical: 'v091_proactive_messages', aliases: { postgres: 'v093', 'sqlite-sql': 'v091' }, classification: 'schema-simple', notes: 'ADR-0054 Phase 2: proactive outbound message queue (self-initiated nudges)' },
  { canonical: 'v092_notification_preferences', aliases: { postgres: 'v094', 'sqlite-sql': 'v092' }, classification: 'schema-simple', notes: 'ADR-0054 red-line 9: per-user notification preferences (push opt-in + quiet hours)' },
  { canonical: 'v093_companion_identity', aliases: { postgres: 'v095', 'sqlite-sql': 'v093' }, classification: 'schema-simple', notes: 'ADR-0055 self-awareness: per-persona first-person identity (name)' },
  { canonical: 'v094_memory_translations', aliases: { postgres: 'v096', 'sqlite-sql': 'v094' }, classification: 'schema-simple', notes: 'ADR-0055 content multilingual: per-language memory content variants' },
  { canonical: 'v095_companion_mood', aliases: { postgres: 'v097', 'sqlite-sql': 'v095' }, classification: 'schema-simple', notes: 'ADR-0056 humanization: per-persona current mood (valence/arousal)' },
  { canonical: 'v096_companion_relationship', aliases: { postgres: 'v098', 'sqlite-sql': 'v096' }, classification: 'schema-simple', notes: 'ADR-0056 humanization: I-you relationship memory (user name + interaction count)' },
  { canonical: 'v097_digital_workforce', aliases: { postgres: 'v099', 'sqlite-sql': 'v097' }, classification: 'schema-simple', notes: 'Digital workforce M1: org chart + deterministic goal decomposition + delegation/report (zero-LLM)' },
  { canonical: 'v098_workforce_task_contract', aliases: { postgres: 'v100', 'sqlite-sql': 'v098' }, classification: 'schema-simple', notes: 'Digital workforce A0: org_tasks contract fields (risk/tool-eligible/acceptance/capabilities)' },
  { canonical: 'v099_workforce_collaboration', aliases: { postgres: 'v101', 'sqlite-sql': 'v099' }, classification: 'schema-simple', notes: 'Digital workforce B1: structured agent-to-agent collaboration (threads + messages)' },
  { canonical: 'v100_workforce_handoff', aliases: { postgres: 'v102', 'sqlite-sql': 'v100' }, classification: 'schema-simple', notes: 'Digital workforce B2: task handoff negotiation (proposed/accepted/rejected/cancelled)' },
  { canonical: 'v101_worker_collaboration_memory', aliases: { postgres: 'v103', 'sqlite-sql': 'v101' }, classification: 'schema-simple', notes: 'Digital workforce C1: per-counterpart collaboration memory (fixes cross-contamination)' },
  { canonical: 'v102_org_approvals', aliases: { postgres: 'v104', 'sqlite-sql': 'v102' }, classification: 'schema-simple', notes: 'Digital workforce D2: execution approval gate (ADR-0055 risk-tiered)' },
  { canonical: 'v103_org_escalations', aliases: { postgres: 'v105', 'sqlite-sql': 'v103' }, classification: 'schema-simple', notes: 'Digital workforce B-chain: multi-level escalation chain (blocked worker escalates up reporting line)' },
  { canonical: 'v104_org_tasks_due_at', aliases: { postgres: 'v106', 'sqlite-sql': 'v104' }, classification: 'schema-simple', notes: 'Digital workforce C-chain: org_tasks.due_at (task SLA deadline for temporal awareness)' },
  { canonical: 'v105_org_goals_playbook_version', aliases: { postgres: 'v107', 'sqlite-sql': 'v105' }, classification: 'schema-simple', notes: 'Digital workforce M2: org_goals.playbook_version (versioned rule-pack audit)' },
  { canonical: 'v106_persona_id_core_isolation', aliases: { postgres: 'v108', 'sqlite-sql': 'v106' }, classification: 'schema-raw', notes: 'K1 ADR-0056: per-(tenant, persona) cognitive core isolation — add persona_id column only (default default) + composite index; no PK/unique change (PK + executor change deferred to K2)' },
  { canonical: 'v107_persona_character_pk', aliases: { postgres: 'v109', 'sqlite-sql': 'v107' }, classification: 'schema-raw', notes: 'K2 ADR-0056: composite (tenant_id, persona_id) PK on decision_style/cognitive_model/narrative (atomic with executor ON CONFLICT change)' },
  { canonical: 'v108_learning_requests', aliases: { postgres: 'v110', 'sqlite-sql': 'v108' }, classification: 'schema-simple', notes: 'Job-function learning L2 (ADR-0057): learning_requests ledger (gap → request; idempotent active per (tenant,persona,capability); is_unknown lint marker; per-persona)' },
  { canonical: 'v109_capability_index', aliases: { postgres: 'v111', 'sqlite-sql': 'v109' }, classification: 'schema-simple', notes: 'Job-function learning L7 (ADR-0057): capability_index — formal learned-capabilities source projected from capability-learned event (replaces L2 listPassedCapabilities scan; per-persona; unique per (tenant,persona,capability))' },
  { canonical: 'v110_org_tasks_resume_guard', aliases: { postgres: 'v112', 'sqlite-sql': 'v110' }, classification: 'schema-simple', notes: 'Job-function learning L8a (ADR-0057 D0.8): org_tasks resume_attempt_count + last_wake_event_id (learning wake idempotency + anti-loop guard; blocked_on_capabilities is derived not stored)' },
  { canonical: 'v111_org_wallet', aliases: { postgres: 'v113', 'sqlite-sql': 'v111' }, classification: 'schema-simple', notes: 'Digital workforce: org_wallets (organization-level treasury so an org can earn from the task marketplace; (tenant,org) unique)' },
  { canonical: 'v112_bidirectional_task_market', aliases: { postgres: 'v114', 'sqlite-sql': 'v112' }, classification: 'schema-simple', notes: 'Bidirectional task market (ADR-0058): marketplace_tasks +assignee_kind/org_id/publisher_verified + parallel task_org_applications/assignments (org bids alongside personas; publisher confirms)' },
  { canonical: 'v113_tool_action_rules', aliases: { postgres: 'v115', 'sqlite-sql': 'v113' }, classification: 'schema-simple', notes: 'Tool action rules (ADR-0060 T1): deterministic tool-call argument construction rules (runtime zero-LLM); (tenant,persona,tool,capability,schema_version) partial-unique on active' },
  { canonical: 'v114_tool_action_rule_provenance', aliases: { postgres: 'v116', 'sqlite-sql': 'v114' }, classification: 'schema-simple', notes: 'Tool action rule provenance (ADR-0060 T3, 红线 6): source_artifact_id links each rule to its upstream distillation artifact (source traceable, no direct injection)' },
  { canonical: 'v115_tool_action_rule_eligibility_provenance', aliases: { postgres: 'v117', 'sqlite-sql': 'v115' }, classification: 'schema-simple', notes: 'Tool action rule eligibility provenance (ADR-0060 T4, 红线 11): exam_spec_version + risk_class so eligibility recommendations can expire on tool schema / risk change' },
  { canonical: 'v116_capability_tool_eligibility', aliases: { postgres: 'v118', 'sqlite-sql': 'v116' }, classification: 'schema-simple', notes: 'Capability→tool eligibility (ADR-0060 T4, 红线 2/11/12): recommendation-only projection (never grant); staleness metadata; (tenant,persona,capability,tool_id) partial-unique on active' },
  { canonical: 'v117_tool_authorization_requests', aliases: { postgres: 'v119', 'sqlite-sql': 'v117' }, classification: 'schema-simple', notes: 'Pending tool authorization requests (ADR-0060 T5, 红线 3): non-whitelisted/high-risk eligibility → manual approval queue (never auto-grant); (tenant,persona,capability,tool_id) partial-unique on pending' },
  { canonical: 'v118_life_simulation_owner', aliases: { postgres: 'v120', 'sqlite-sql': 'v118' }, classification: 'schema-simple', notes: '安全: life_simulations.owner_user_id — 模拟归属权，owner-only 分享鉴权基础（堵同租户抢注分享 + 存在性泄露；历史行 owner=null 保守拒绝）' },
  { canonical: 'v119_github_integration', aliases: { postgres: 'v121', 'sqlite-sql': 'v119' }, classification: 'schema-raw', notes: 'GitHub 集成地基（Plan 1 Task 1）: github_app_credentials（per-tenant App 凭据密文，tenant_id PK 单例）+ github_installations（installation→tenant 映射，UNIQUE(github_host, installation_id) 全局唯一防跨租户 webhook 混淆）' },
  { canonical: 'v120_github_learn_state', aliases: { postgres: 'v122', 'sqlite-sql': 'v120' }, classification: 'schema-raw', notes: 'GitHub 学习段地基（Plan 2 Task 1）: github_learn_state（增量同步游标，(tenant,persona,repo,resource_type) 唯一；resource_type CHECK code/issues/pulls/commits）+ github_ingest_digests（摄入幂等账本，content_sha 指纹，claimed→ingested 两态，(tenant,persona,repo,resource_type,content_sha) 唯一防重复摄入）' },
  { canonical: 'v121_github_reply_drafts', aliases: { postgres: 'v123', 'sqlite-sql': 'v121' }, classification: 'schema-raw', notes: 'GitHub 反馈起草段地基（Plan 3 Task 1）: github_reply_drafts（回复草稿，起草停 drafted 待审批；target_type CHECK issue/pull，status CHECK drafted/approved/rejected）+ github_webhook_events（webhook 幂等，独立于 Stripe webhook_events；复合主键 (tenant_id, delivery_id) 防跨租户 delivery id 相撞）' },
  { canonical: 'v122_github_draft_published', aliases: { postgres: 'v124', 'sqlite-sql': 'v122' }, classification: 'schema-raw', notes: 'GitHub 反馈发布段地基（Plan 4 Task 1）: github_reply_drafts status CHECK 加 published 终态 + published_at（发布时间戳，可空）+ github_ref（GitHub 侧 comment/review id，可空，审计+去重佐证）；PG 原地 ALTER CHECK/ADD COLUMN，SQLite 重建表' },
  { canonical: 'v123_tenant_identity_directory', aliases: { postgres: 'v125', 'sqlite-sql': 'v123' }, classification: 'schema-simple', notes: '租户分片 Phase 0 Plan 1c Task 1: coordinator tenant_identity_directory 目录表（email/refresh_token_hash/api_key_hash 查找键→租户）；operation_kind REGISTER/EMAIL_CHANGE/TOKEN/API_KEY + status PENDING/ACTIVE mixed-scope 状态机地基；UNIQUE(lookup_kind, lookup_value) 全局唯一挡并发 register；无 shard_id（shardId 由 tenantId 纯函数派生）' },
  { canonical: 'v124_tenant_bootstrap_backfill', aliases: { postgres: 'v126', 'sqlite-sql': 'v124' }, classification: 'schema-raw', notes: '租户分片 Phase 0 Plan 1c Task 2（向后兼容硬前置）: tenant_bootstrap 完成标记表（PK (tenant_id, operation_id) per-operation 粒度，status CHECK COMPLETE）+ 历史身份回填（老 users/api_keys/refresh_tokens → tenant_identity_directory ACTIVE 项，operation_id=backfill，逐类 operation_kind REGISTER/TOKEN/API_KEY）；email 归一化贯穿（lookup_value=LOWER(TRIM) + 同步归一化 users.email）；归一化后重复 email fail-closed 抛错停止（SQLite 临时表唯一约束 / PG DO RAISE）；幂等（SQLite INSERT OR IGNORE / PG ON CONFLICT DO NOTHING）；数据迁移故用 raw' },
  { canonical: 'v125_github_digest_discussion_key', aliases: { postgres: 'v127', 'sqlite-sql': 'v125' }, classification: 'schema-raw', notes: 'GitHub 讨论内容摄入：github_ingest_digests 加 discussion_key（issues:owner/repo#42 讨论稳定标识，可空）+ memory_id（该讨论当前记忆指针，可空）+ (tenant_id, persona_id, discussion_key) 二级索引；contentSha 含评论后随讨论变化致去重账本失效，故用稳定讨论键 + 记忆指针实现演进式取代（新记忆沉淀后删同讨论旧记忆，每 issue 恒为一条最新共识）；纯加列不重建表，规避 SQLite 重建丢索引坑' },
];
