import type { RendererTarget } from './types.js';

export interface VersionMapEntry {
  readonly canonical: string;
  readonly aliases: Partial<Record<RendererTarget, string>>;
  readonly classification: 'schema-simple' | 'schema-raw' | 'pg-only' | 'disabled';
  readonly notes?: string;
}

export const VERSION_MAP: readonly VersionMapEntry[] = [
  { canonical: 'v001', aliases: { postgres: 'v001', 'sqlite-sql': 'v001' }, classification: 'schema-simple' },
  { canonical: 'v002', aliases: { postgres: 'v002', 'sqlite-sql': 'v002' }, classification: 'schema-simple' },
  { canonical: 'v003', aliases: { postgres: 'v003', 'sqlite-sql': 'v003' }, classification: 'schema-simple' },
  { canonical: 'v004', aliases: { postgres: 'v004', 'sqlite-sql': 'v004' }, classification: 'schema-simple' },
  { canonical: 'v005', aliases: { postgres: 'v005', 'sqlite-sql': 'v005' }, classification: 'schema-simple' },
  { canonical: 'v006', aliases: { postgres: 'v006', 'sqlite-sql': 'v006' }, classification: 'schema-simple' },
  { canonical: 'v007', aliases: { postgres: 'v007', 'sqlite-sql': 'v007' }, classification: 'schema-raw', notes: 'SQLite 表重建 vs PG 原地 ALTER' },
  { canonical: 'v008', aliases: { postgres: 'v008', 'sqlite-sql': 'v008' }, classification: 'schema-simple' },
  { canonical: 'v009', aliases: { postgres: 'v009', 'sqlite-sql': 'v009' }, classification: 'schema-simple' },
  { canonical: 'v010', aliases: { postgres: 'v010', 'sqlite-sql': 'v010' }, classification: 'schema-simple' },
  { canonical: 'v011', aliases: { postgres: 'v011', 'sqlite-sql': 'v011' }, classification: 'schema-simple' },
  { canonical: 'v012', aliases: { postgres: 'v012', 'sqlite-sql': 'v012' }, classification: 'schema-simple' },
  { canonical: 'v013', aliases: { postgres: 'v013', 'sqlite-sql': 'v013' }, classification: 'schema-simple' },
  { canonical: 'v014', aliases: { postgres: 'v014', 'sqlite-sql': 'v014' }, classification: 'schema-simple' },
  { canonical: 'v015', aliases: { postgres: 'v015', 'sqlite-sql': 'v015' }, classification: 'schema-simple' },
  { canonical: 'v016', aliases: { postgres: 'v016', 'sqlite-sql': 'v016' }, classification: 'schema-simple' },
  { canonical: 'v017', aliases: { postgres: 'v017', 'sqlite-sql': 'v017' }, classification: 'schema-simple' },
  { canonical: 'v018', aliases: { postgres: 'v018', 'sqlite-sql': 'v018' }, classification: 'schema-simple' },
  { canonical: 'v019', aliases: { postgres: 'v019', 'sqlite-sql': 'v019' }, classification: 'schema-simple' },
  { canonical: 'v020', aliases: { postgres: 'v020', 'sqlite-sql': 'v020' }, classification: 'schema-simple' },
  { canonical: 'v021', aliases: { postgres: 'v021', 'sqlite-sql': 'v021' }, classification: 'schema-simple' },
  { canonical: 'v022', aliases: { postgres: 'v022', 'sqlite-sql': 'v022' }, classification: 'schema-simple' },
  { canonical: 'v023', aliases: { postgres: 'v023', 'sqlite-sql': 'v023' }, classification: 'schema-simple' },
  { canonical: 'v024', aliases: { postgres: 'v024', 'sqlite-sql': 'v024' }, classification: 'schema-simple' },
  { canonical: 'v025', aliases: { postgres: 'v025', 'sqlite-sql': 'v025' }, classification: 'schema-simple' },
  { canonical: 'v026', aliases: { postgres: 'v026', 'sqlite-sql': 'v026' }, classification: 'schema-simple' },
  { canonical: 'v027', aliases: { postgres: 'v027', 'sqlite-sql': 'v027' }, classification: 'schema-raw', notes: 'identities/avatars 回填 DML' },
  { canonical: 'v028', aliases: { postgres: 'v028', 'sqlite-sql': 'v028' }, classification: 'schema-simple' },
  { canonical: 'v029', aliases: { postgres: 'v029', 'sqlite-sql': 'v029' }, classification: 'schema-simple' },
  { canonical: 'v030', aliases: { postgres: 'v030', 'sqlite-sql': 'v030' }, classification: 'schema-raw', notes: 'CHECK 约束改写' },
  { canonical: 'v031', aliases: { postgres: 'v031', 'sqlite-sql': 'v031' }, classification: 'schema-simple' },
  { canonical: 'v032', aliases: { postgres: 'v032', 'sqlite-sql': 'v032' }, classification: 'schema-simple' },
  { canonical: 'v033', aliases: { postgres: 'v033', 'sqlite-sql': 'v033' }, classification: 'schema-simple' },
  { canonical: 'v034', aliases: { postgres: 'v034', 'sqlite-sql': 'v034' }, classification: 'schema-raw', notes: 'lifecycle_status 回填；NULL 语义差异原样保留' },
  { canonical: 'v035', aliases: { postgres: 'v035', 'sqlite-sql': 'v035' }, classification: 'schema-simple' },
  { canonical: 'v036', aliases: { postgres: 'v036', 'sqlite-sql': 'v036' }, classification: 'schema-simple' },
  { canonical: 'v037', aliases: { postgres: 'v037', 'sqlite-sql': 'v037' }, classification: 'schema-simple' },
  { canonical: 'v038', aliases: { postgres: 'v038', 'sqlite-sql': 'v038' }, classification: 'schema-simple' },
  { canonical: 'v039', aliases: { postgres: 'v039', 'sqlite-sql': 'v039' }, classification: 'schema-simple' },
  { canonical: 'v040', aliases: { postgres: 'v040', 'sqlite-sql': 'v040' }, classification: 'schema-raw', notes: 'audit_log 回填 UPDATE' },
  { canonical: 'v041', aliases: { postgres: 'v041', 'sqlite-sql': 'v041' }, classification: 'schema-raw', notes: 'runtime_sessions 重建/CHECK/UPDATE' },
  { canonical: 'v042', aliases: { postgres: 'v042', 'sqlite-sql': 'v042' }, classification: 'schema-simple' },
  { canonical: 'v043', aliases: { postgres: 'v043', 'sqlite-sql': 'v043' }, classification: 'schema-simple' },
  { canonical: 'v044', aliases: { postgres: 'v044', 'sqlite-sql': 'v044' }, classification: 'schema-simple' },
  { canonical: 'v045', aliases: { postgres: 'v045', 'sqlite-sql': 'v045' }, classification: 'schema-simple' },
  { canonical: 'v046', aliases: { postgres: 'v046', 'sqlite-sql': 'v046' }, classification: 'schema-simple' },
  { canonical: 'v047', aliases: { postgres: 'v047', 'sqlite-sql': 'v047' }, classification: 'schema-raw', notes: 'identity/avatar 多表重建' },
  { canonical: 'v048', aliases: { postgres: 'v048', 'sqlite-sql': 'v048' }, classification: 'schema-simple' },
  { canonical: 'v049', aliases: { postgres: 'v049', 'sqlite-sql': 'v049' }, classification: 'schema-simple' },
  { canonical: 'v050', aliases: { postgres: 'v050', 'sqlite-sql': 'v050' }, classification: 'schema-simple' },
  { canonical: 'v051', aliases: { postgres: 'v051', 'sqlite-sql': 'v051' }, classification: 'schema-simple' },
  { canonical: 'v052', aliases: { postgres: 'v052', 'sqlite-sql': 'v052' }, classification: 'schema-raw', notes: 'event_ledger_authority 单例 seed' },
  { canonical: 'v053', aliases: { postgres: 'v053', 'sqlite-sql': 'v053' }, classification: 'schema-simple' },
  { canonical: 'v054', aliases: { postgres: 'v054', 'sqlite-sql': 'v054' }, classification: 'schema-simple' },
  { canonical: 'v055', aliases: { postgres: 'v055', 'sqlite-sql': 'v055' }, classification: 'schema-simple' },
  { canonical: 'v056', aliases: { postgres: 'v056', 'sqlite-sql': 'v056' }, classification: 'schema-simple' },
  { canonical: 'v057', aliases: { postgres: 'v057', 'sqlite-sql': 'v057' }, classification: 'schema-simple' },
  { canonical: 'v058', aliases: { postgres: 'v058', 'sqlite-sql': 'v058' }, classification: 'schema-simple' },
  { canonical: 'v059', aliases: { postgres: 'v059', 'sqlite-sql': 'v059' }, classification: 'schema-simple' },
  { canonical: 'v060', aliases: { postgres: 'v060', 'sqlite-sql': 'v060' }, classification: 'schema-simple' },
  { canonical: 'v061', aliases: { postgres: 'v061', 'sqlite-sql': 'v061' }, classification: 'schema-simple' },
  { canonical: 'v062', aliases: { postgres: 'v062', 'sqlite-sql': 'v062' }, classification: 'schema-simple' },
  { canonical: 'v063', aliases: { postgres: 'v063', 'sqlite-sql': 'v063' }, classification: 'schema-simple' },
  { canonical: 'v064', aliases: { postgres: 'v064', 'sqlite-sql': 'v064' }, classification: 'schema-simple' },
  { canonical: 'v065', aliases: { postgres: 'v065', 'sqlite-sql': 'v065' }, classification: 'schema-simple' },
  { canonical: 'v066', aliases: { postgres: 'v066', 'sqlite-sql': 'v066' }, classification: 'schema-simple' },
  { canonical: 'v067', aliases: { postgres: 'v067', 'sqlite-sql': 'v067' }, classification: 'schema-simple' },
  { canonical: 'v068', aliases: { postgres: 'v068', 'sqlite-sql': 'v068' }, classification: 'schema-simple' },
  { canonical: 'v069', aliases: { postgres: 'v069', 'sqlite-sql': 'v069' }, classification: 'schema-simple' },
  { canonical: 'v070', aliases: { postgres: 'v070', 'sqlite-sql': 'v070' }, classification: 'schema-simple' },
  { canonical: 'v071_pg', aliases: { postgres: 'v071' }, classification: 'pg-only', notes: 'pgvector + HNSW + trigger' },
  { canonical: 'v072_pg', aliases: { postgres: 'v072' }, classification: 'disabled', notes: 'pgvector stage 7 — ships when ramp completes' },
  { canonical: 'v071_sqlite_devices_token', aliases: { postgres: 'v073', 'sqlite-sql': 'v071' }, classification: 'schema-simple', notes: 'EP-3.5 token invalidation; alias skew' },
  { canonical: 'v072_onboarding_v2', aliases: { postgres: 'v074', 'sqlite-sql': 'v072' }, classification: 'schema-simple', notes: 'W2.1 agent-governance onboarding; PG skips v072(disabled)/v073(devices)' },
  { canonical: 'v073_audit_hash_chain', aliases: { postgres: 'v075', 'sqlite-sql': 'v073' }, classification: 'schema-simple', notes: 'P0-E: audit_log append-only hash chain columns' },
  { canonical: 'v074_soc2_evidence', aliases: { postgres: 'v076', 'sqlite-sql': 'v074' }, classification: 'schema-simple', notes: 'P1-F-basic: SOC2 evidence collection table' },
  { canonical: 'v075_legal_holds', aliases: { postgres: 'v077', 'sqlite-sql': 'v075' }, classification: 'schema-simple', notes: 'P1-N: legal holds registry' },
  { canonical: 'v076_break_glass_jti_consumptions', aliases: { postgres: 'v078', 'sqlite-sql': 'v076' }, classification: 'schema-simple', notes: 'P1-M v2: durable break-glass JTI replay ledger' },
  { canonical: 'v077_audit_chain_anchors', aliases: { postgres: 'v079', 'sqlite-sql': 'v077' }, classification: 'schema-simple', notes: 'P0-E v2: KMS-signed audit chain tail anchors' },
];
