# DEPRECATED: use chrono-synth-deploy/k8s/ instead
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chrono-synth-observability-worker
  namespace: chrono-synth
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: chrono-synth-observability-worker
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 3100
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: monitoring
      ports:
        - protocol: TCP
          port: 3100
