apiVersion: v1
kind: Service
metadata:
  name: chrono-synth-observability-worker
  namespace: chrono-synth
  labels:
    app.kubernetes.io/name: chrono-synth-observability-worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chrono-synth-observability-worker
  ports:
    - name: monitor
      port: 3100
      targetPort: monitor
      protocol: TCP
