apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chrono-synth-data
  namespace: chrono-synth
  labels:
    app.kubernetes.io/name: chrono-synth-os
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
