import type { Migration, RenderedMigration } from '../types.js';
import { SqliteRustRenderer } from './sqlite-rust.js';

export interface RustModuleOptions {
  readonly migrations: readonly Migration[];
  readonly packageHeader?: string;
}

export function renderRustModule(opts: RustModuleOptions): string {
  const renderer = new SqliteRustRenderer();
  const rendered = opts.migrations
    .filter(migration => migration.aliases['sqlite-rust'])
    .map(migration => renderer.renderMigration(migration, { target: 'sqlite-rust' }))
    .filter((migration): migration is RenderedMigration => migration !== null);

  const lines = [
    '// AUTO-GENERATED by @chrono/schema-dsl. DO NOT EDIT.',
    `// Source: ${opts.packageHeader ?? 'packages/schema-dsl/src/migrations/desktop/'}`,
    '',
    'pub struct GeneratedMigration {',
    '    pub version: i64,',
    "    pub description: &'static str,",
    "    pub sql: &'static str,",
    '}',
    '',
    'pub const DESKTOP_MIGRATIONS: &[GeneratedMigration] = &[',
  ];

  for (const migration of rendered) {
    const sql = migration.sql.join('\n;\n');
    const delimiter = rustRawStringDelimiter(sql);
    lines.push(
      '    GeneratedMigration {',
      `        version: ${renderRustVersion(migration.version)},`,
      `        description: "${escapeRustString(migration.description)}",`,
      `        sql: ${delimiter.open}${sql}${delimiter.close},`,
      '    },',
    );
  }

  lines.push('];', '');
  return lines.join('\n');
}

function renderRustVersion(version: string): number {
  const match = /^v?(\d+)$/.exec(version);
  if (!match) throw new Error(`sqlite-rust migration version must be numeric or v-prefixed: ${version}`);
  return Number.parseInt(match[1], 10);
}

function escapeRustString(value: string): string {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('\r', '\\r')
    .replaceAll('\n', '\\n');
}

function rustRawStringDelimiter(sql: string): { open: string; close: string } {
  for (let hashes = 1; hashes <= 16; hashes += 1) {
    const marker = `${'"'}${'#'.repeat(hashes)}`;
    if (!sql.includes(marker)) {
      const fence = '#'.repeat(hashes);
      return { open: `r${fence}"`, close: `"${fence}` };
    }
  }
  throw new Error('SQL contains too many Rust raw string fence markers');
}
