import { defineMigration, type Migration } from '../../index.js';

export const v001_initial_schema: Migration = defineMigration({
  kind: 'schema',
  id: 'initial-schema',
  aliases: { postgres: 'v001', 'sqlite-sql': 'v001' },
  description: '初始表结构',
  operations: [
    { kind: 'create-table', table: { name: 'core_values', ifNotExists: true, columns: [
      { name: 'id', type: 'text', primaryKey: true },
      { name: 'label', type: 'text', nullable: false },
      { name: 'weight', type: 'real', nullable: false, check: 'weight >= 0 AND weight <= 1' },
      { name: 'updated_at', type: 'bigint', nullable: false },
    ] } },
    { kind: 'create-table', table: { name: 'memory_nodes', ifNotExists: true, columns: [
      { name: 'id', type: 'text', primaryKey: true },
      { name: 'kind', type: 'text', nullable: false, check: "kind IN ('episodic', 'semantic', 'procedural')" },
      { name: 'content', type: 'text', nullable: false },
      { name: 'valence', type: 'real', nullable: false, check: 'valence >= -1 AND valence <= 1' },
      { name: 'salience', type: 'real', nullable: false, check: 'salience >= 0 AND salience <= 1' },
      { name: 'created_at', type: 'bigint', nullable: false },
      { name: 'last_accessed_at', type: 'bigint', nullable: false },
    ] } },
    { kind: 'create-table', table: { name: 'memory_edges', ifNotExists: true, columns: [
      { name: 'source', type: 'text', nullable: false, references: { table: 'memory_nodes', column: 'id' } },
      { name: 'target', type: 'text', nullable: false, references: { table: 'memory_nodes', column: 'id' } },
      { name: 'strength', type: 'real', nullable: false, check: 'strength >= 0 AND strength <= 1' },
      { name: 'relation', type: 'text', nullable: false },
    ], constraints: [{ kind: 'primary-key', columns: ['source', 'target'] }] } },
    { kind: 'create-table', table: { name: 'narrative', ifNotExists: true, columns: [
      { name: 'id', type: 'integer', primaryKey: true, check: 'id = 1' },
      { name: 'content', type: 'text', nullable: false },
      { name: 'updated_at', type: 'bigint', nullable: false },
    ] } },
    { kind: 'create-table', table: { name: 'persona_versions', ifNotExists: true, columns: [
      { name: 'id', type: 'text', primaryKey: true },
      { name: 'label', type: 'text', nullable: false },
      { name: 'values_json', type: 'text', nullable: false },
      { name: 'status', type: 'text', nullable: false, check: "status IN ('active', 'paused', 'completed', 'failed')" },
      { name: 'results_json', type: 'text', nullable: false, default: '[]' },
      { name: 'resource_quota', type: 'real', nullable: false, check: 'resource_quota >= 0 AND resource_quota <= 1' },
      { name: 'created_at', type: 'bigint', nullable: false },
      { name: 'updated_at', type: 'bigint', nullable: false },
    ] } },
    { kind: 'create-table', table: { name: 'conflicts', ifNotExists: true, columns: [
      { name: 'id', type: 'text', primaryKey: true },
      { name: 'kind', type: 'text', nullable: false },
      { name: 'severity', type: 'text', nullable: false },
      { name: 'involved_versions_json', type: 'text', nullable: false },
      { name: 'affected_values_json', type: 'text', nullable: false },
      { name: 'description', type: 'text', nullable: false },
      { name: 'detected_at', type: 'bigint', nullable: false },
      { name: 'resolved_at', type: 'bigint' },
      { name: 'resolution', type: 'text' },
    ] } },
    { kind: 'create-table', table: { name: 'snapshots', ifNotExists: true, columns: [
      { name: 'id', type: 'text', primaryKey: true },
      { name: 'data_json', type: 'text', nullable: false },
      { name: 'reason', type: 'text', nullable: false },
      { name: 'created_at', type: 'bigint', nullable: false },
    ] } },
    { kind: 'create-table', table: { name: 'evolution_records', ifNotExists: true, columns: [
      { name: 'id', type: 'text', primaryKey: true },
      { name: 'before_snapshot_id', type: 'text', nullable: false, references: { table: 'snapshots', column: 'id' } },
      { name: 'after_snapshot_id', type: 'text', nullable: false, references: { table: 'snapshots', column: 'id' } },
      { name: 'merged_version_ids_json', type: 'text', nullable: false },
      { name: 'value_delta_json', type: 'text', nullable: false },
      { name: 'evolved_at', type: 'bigint', nullable: false },
    ] } },
    { kind: 'create-index', index: { name: 'idx_persona_status', table: 'persona_versions', columns: ['status'], ifNotExists: true } },
    { kind: 'create-index', index: { name: 'idx_conflicts_resolved_at', table: 'conflicts', columns: ['resolved_at'], ifNotExists: true } },
    { kind: 'create-index', index: { name: 'idx_snapshots_created_at', table: 'snapshots', columns: ['created_at'], ifNotExists: true } },
    { kind: 'create-index', index: { name: 'idx_memory_edges_target', table: 'memory_edges', columns: ['target'], ifNotExists: true } },
  ],
});
