//! Versioned migration runner for the desktop SQLite database.
//!
//! Schema mirrors a *subset* of the chrono-synth-os server schema — the tables
//! a single-user desktop client needs for offline persona viewing, memory
//! inspection, and queued sync. Server-only concerns (multi-tenant, billing,
//! RBAC) are intentionally excluded.
//!
//! Migrations are forward-only and idempotent. The applied schema is owned
//! by `@chrono/schema-dsl`; this file invokes the generated migration table
//! produced by build.rs at compile time.

use anyhow::{Context, Result};
use rusqlite::Connection;

// Generated by build.rs from @chrono/schema-dsl. See src-tauri/build.rs.
include!(concat!(env!("OUT_DIR"), "/migrations_generated.rs"));

/// Run all pending migrations in version order. Idempotent.
pub fn run_migrations(conn: &Connection) -> Result<()> {
    conn.execute_batch(
        r#"
        PRAGMA foreign_keys = ON;

        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            description TEXT NOT NULL,
            applied_at INTEGER NOT NULL DEFAULT (unixepoch('now') * 1000)
        );
        "#,
    )?;

    for migration in DESKTOP_MIGRATIONS {
        let already_applied: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM schema_migrations WHERE version = ?1",
                [migration.version],
                |row| row.get(0),
            )
            .with_context(|| format!("checking migration v{}", migration.version))?;
        if already_applied > 0 {
            continue;
        }

        conn.execute_batch(migration.sql).with_context(|| {
            format!(
                "applying migration v{}: {}",
                migration.version, migration.description
            )
        })?;

        conn.execute(
            "INSERT INTO schema_migrations (version, description) VALUES (?1, ?2)",
            (migration.version, migration.description),
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use rusqlite::Connection;

    fn open_in_memory() -> Connection {
        let conn = Connection::open_in_memory().expect("open in-memory db");
        run_migrations(&conn).expect("migrations apply");
        conn
    }

    #[test]
    fn applies_all_migrations_idempotently() {
        let conn = open_in_memory();
        // Re-running should be a no-op.
        run_migrations(&conn).expect("re-run is idempotent");

        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM schema_migrations", [], |r| r.get(0))
            .unwrap();
        assert_eq!(count, 7, "all seven versions should be recorded");
    }

    #[test]
    fn app_settings_round_trips_kv_pair() {
        let conn = open_in_memory();
        conn.execute(
            "INSERT INTO app_settings (key, value) VALUES ('onboarding.first_run_completed', '1')",
            [],
        )
        .expect("insert succeeds");

        let value: String = conn
            .query_row(
                "SELECT value FROM app_settings WHERE key = ?1",
                ["onboarding.first_run_completed"],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(value, "1");
    }

    #[test]
    fn app_settings_primary_key_dedupes_on_replace() {
        let conn = open_in_memory();
        conn.execute(
            "INSERT INTO app_settings (key, value) VALUES (?1, ?2)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = unixepoch('now') * 1000",
            ["theme", "dark"],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO app_settings (key, value) VALUES (?1, ?2)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = unixepoch('now') * 1000",
            ["theme", "light"],
        )
        .unwrap();

        let value: String = conn
            .query_row(
                "SELECT value FROM app_settings WHERE key = 'theme'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(value, "light", "second upsert should overwrite first");

        let count: i64 = conn
            .query_row("SELECT COUNT(*) FROM app_settings", [], |r| r.get(0))
            .unwrap();
        assert_eq!(count, 1, "PK should dedupe");
    }

    #[test]
    fn rejects_invalid_memory_valence() {
        let conn = open_in_memory();
        conn.execute(
            "INSERT INTO personas (persona_id, display_name, updated_at) VALUES ('p1', 'P', '2026-01-01T00:00:00Z')",
            [],
        )
        .unwrap();

        let bad = conn.execute(
            r#"INSERT INTO memory_nodes
               (id, persona_id, kind, content, valence, salience, created_at, last_accessed_at)
               VALUES ('m1', 'p1', 'episodic', 'hi', 2.0, 0.5, 0, 0)"#,
            [],
        );
        assert!(bad.is_err(), "valence > 1 must be rejected by CHECK");

        let good = conn.execute(
            r#"INSERT INTO memory_nodes
               (id, persona_id, kind, content, valence, salience, created_at, last_accessed_at)
               VALUES ('m2', 'p1', 'episodic', 'hi', 0.5, 0.5, 0, 0)"#,
            [],
        );
        assert!(good.is_ok(), "valence within range must succeed");
    }

    #[test]
    fn cascades_persona_delete_to_memories() {
        let conn = open_in_memory();
        conn.execute(
            "INSERT INTO personas (persona_id, display_name, updated_at) VALUES ('p1', 'P', '2026-01-01T00:00:00Z')",
            [],
        )
        .unwrap();
        conn.execute(
            r#"INSERT INTO memory_nodes (id, persona_id, kind, content, valence, salience, created_at, last_accessed_at)
               VALUES ('m1', 'p1', 'episodic', 'hi', 0.0, 0.5, 0, 0)"#,
            [],
        )
        .unwrap();

        conn.execute("DELETE FROM personas WHERE persona_id = 'p1'", [])
            .unwrap();
        let remaining: i64 = conn
            .query_row("SELECT COUNT(*) FROM memory_nodes", [], |r| r.get(0))
            .unwrap();
        assert_eq!(remaining, 0, "memories should cascade-delete with persona");
    }
}
