import { defineRaw, rawSql } from '../../dsl/raw.js';

export const v040_audit_log_backfill: ReturnType<typeof defineRaw> = defineRaw({
  id: 'audit-log-backfill',
  version: 'v040',
  aliases: { postgres: 'v040', 'sqlite-sql': 'v040' },
  description: 'audit_log 业务级审计回填',
  reason: '包含 audit_log 扩展列与历史行 UPDATE 回填',
  postgres: rawSql([
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS created_at BIGINT NOT NULL DEFAULT 0`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS event_kind TEXT NOT NULL DEFAULT 'request'`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_id TEXT`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS user_email TEXT`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS action_type TEXT DEFAULT 'other'`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS actor_type TEXT`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS actor_id TEXT`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS target_type TEXT`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS target_id TEXT`,
    `ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS payload_json TEXT`,
    `UPDATE audit_log SET created_at = timestamp WHERE created_at = 0`,
    `CREATE INDEX IF NOT EXISTS idx_audit_log_tenant_created_at ON audit_log(tenant_id, created_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log(tenant_id, actor_id, created_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_audit_log_target ON audit_log(tenant_id, target_type, target_id, created_at DESC)`,
  ]),
  sqlite: rawSql([
    `/* safe:add-column:audit_log:created_at */ ALTER TABLE audit_log ADD COLUMN created_at INTEGER NOT NULL DEFAULT 0`,
    `/* safe:add-column:audit_log:event_kind */ ALTER TABLE audit_log ADD COLUMN event_kind TEXT NOT NULL DEFAULT 'request'`,
    `/* safe:add-column:audit_log:user_id */ ALTER TABLE audit_log ADD COLUMN user_id TEXT`,
    `/* safe:add-column:audit_log:user_email */ ALTER TABLE audit_log ADD COLUMN user_email TEXT`,
    `/* safe:add-column:audit_log:action_type */ ALTER TABLE audit_log ADD COLUMN action_type TEXT DEFAULT 'other'`,
    `/* safe:add-column:audit_log:actor_type */ ALTER TABLE audit_log ADD COLUMN actor_type TEXT`,
    `/* safe:add-column:audit_log:actor_id */ ALTER TABLE audit_log ADD COLUMN actor_id TEXT`,
    `/* safe:add-column:audit_log:target_type */ ALTER TABLE audit_log ADD COLUMN target_type TEXT`,
    `/* safe:add-column:audit_log:target_id */ ALTER TABLE audit_log ADD COLUMN target_id TEXT`,
    `/* safe:add-column:audit_log:payload_json */ ALTER TABLE audit_log ADD COLUMN payload_json TEXT`,
    `UPDATE audit_log SET created_at = timestamp WHERE created_at = 0`,
    `CREATE INDEX IF NOT EXISTS idx_audit_log_tenant_created_at ON audit_log(tenant_id, created_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON audit_log(tenant_id, actor_id, created_at DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_audit_log_target ON audit_log(tenant_id, target_type, target_id, created_at DESC)`,
  ]),
});
