apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chrono-synth-observability-worker
  namespace: chrono-synth-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chrono-synth-observability-worker
